use axum::extract::FromRequestParts;
use axum::http::request::Parts;
use crate::api::AppState;

macro_rules! define_dict {
    (
        $( $key:ident : { es: $es:expr, en: $en:expr } ),* $(,)?
    ) => {
        /// Dictionary structure holding all the UI strings for the dashboard.
        #[derive(Debug, Clone)]
        pub struct Dict {
            $( pub $key: &'static str, )*
        }

        pub const ES: Dict = Dict {
            $( $key: $es, )*
        };

        pub const EN: Dict = Dict {
            $( $key: $en, )*
        };
    };
}

define_dict! {
    // Navbar
    nav_docs: { es: "Documentación", en: "Documentation" },
    nav_dashboard: { es: "Dashboard", en: "Dashboard" },
    nav_login: { es: "Iniciar Sesión", en: "Sign In" },
    nav_logout: { es: "Cerrar sesión", en: "Log out" },
    btn_new_project: { es: "Nuevo Proyecto", en: "New Project" },
    modal_new_title: { es: "Subir Nuevo Proyecto", en: "Upload New Project" },
    modal_new_name: { es: "Nombre del Proyecto (minúsculas, sin espacios)", en: "Project Name (lowercase, no spaces)" },
    modal_new_file: { es: "Ejecutable o Bundle (.tar.gz con assets)", en: "Executable or Bundle (.tar.gz with assets)" },
    modal_new_submit: { es: "Subir y Desplegar", en: "Upload and Deploy" },
    modal_new_uploading: { es: "Subiendo...", en: "Uploading..." },
    api_key_title: { es: "Tus Credenciales CLI", en: "Your CLI Credentials" },
    api_key_desc: { es: "Usa este comando para hacer deploy desde tu terminal usando curl.", en: "Use this command to deploy from your terminal using curl." },
    api_key_copy: { es: "Copiar Comando", en: "Copy Command" },
    
    // Login
    login_title: { es: "Acceder a ", en: "Sign in to " },
    login_user: { es: "Usuario", en: "Username" },
    login_pass: { es: "Contraseña", en: "Password" },
    login_btn: { es: "Iniciar Sesión", en: "Sign In" },
    login_back: { es: "← Volver al inicio", en: "← Back to home" },
    login_err_pass: { es: "Contraseña incorrecta", en: "Incorrect password" },
    login_err_user: { es: "Usuario no encontrado", en: "User not found" },
    login_err_internal: { es: "Error interno", en: "Internal error" },
    login_register_link: { es: "¿No tienes cuenta? Regístrate", en: "No account? Register" },

    // Register
    reg_title: { es: "Crear cuenta en ", en: "Create account on " },
    reg_btn: { es: "Registrarse", en: "Register" },
    reg_err_exists: { es: "El usuario ya existe", en: "User already exists" },
    reg_err_len: { es: "Contraseña muy corta", en: "Password too short" },
    reg_login_link: { es: "¿Ya tienes cuenta? Inicia sesión", en: "Already have an account? Sign in" },

    // Dashboard Index
    idx_title: { es: "Proyectos", en: "Projects" },
    idx_subtitle_apps: { es: "aplicaciones desplegadas", en: "deployed applications" },
    idx_new_deploy: { es: "+ Nuevo Deploy", en: "+ New Deploy" },
    idx_no_projects: { es: "Sin proyectos aún", en: "No projects yet" },
    idx_deploy_first: { es: "Despliega tu primer binario con:", en: "Deploy your first binary with:" },
    idx_col_name: { es: "Nombre", en: "Name" },
    idx_col_subdomain: { es: "Subdominio", en: "Subdomain" },
    idx_col_port: { es: "Puerto", en: "Port" },
    idx_col_status: { es: "Estado", en: "Status" },
    idx_col_updated: { es: "Actualizado", en: "Updated" },
    idx_col_actions: { es: "Acciones", en: "Actions" },
    idx_how_to_deploy: { es: "Cómo hacer deploy", en: "How to deploy" },

    detail_title: { es: "Detalle del Proyecto", en: "Project Detail" },
    detail_back: { es: "← Volver", en: "← Back" },
    detail_status: { es: "Estado", en: "Status" },
    detail_port: { es: "Puerto", en: "Port" },
    detail_subdomain: { es: "Subdominio", en: "Subdomain" },
    detail_pid: { es: "PID del proceso", en: "Process PID" },
    detail_created: { es: "Creado", en: "Created" },
    detail_updated: { es: "Última Actualización", en: "Last Updated" },
    detail_env: { es: "Variables del Sistema", en: "System Environment" },
    detail_system_env: { es: "Variables del Sistema (Protegidas)", en: "System Variables (Protected)" },
    detail_system_env_desc: { es: "Estas variables son generadas automáticamente por tu servidor privado para garantizar seguridad y aislamiento. No pueden ser modificadas directamente.", en: "These variables are automatically generated by your private server to guarantee security and isolation. They cannot be modified directly." },
    detail_custom_env: { es: "Variables Personalizadas (.env)", en: "Custom Variables (.env)" },
    detail_custom_env_desc: { es: "Estas variables se inyectarán en tu aplicación. Haz clic en Guardar para aplicar y reiniciar el proyecto.", en: "These variables will be injected into your application. Click Save to apply and restart the project." },
    detail_env_save: { es: "💾 Guardar y Reiniciar", en: "💾 Save and Restart" },
    detail_buckets: { es: "Buckets S3 Asociados", en: "Associated S3 Buckets" },
    detail_no_buckets: { es: "Sin buckets aún.", en: "No buckets yet." },
    detail_empty_bucket: { es: "El bucket está vacío.", en: "Bucket is empty." },
    detail_objects: { es: "Objetos", en: "Objects" },
    detail_logs: { es: "Logs de la Aplicación", en: "Application Logs" },
    detail_log_conn: { es: "Conectando...", en: "Connecting..." },

    // Deploy history & rollback
    detail_deploy_history: { es: "Historial de Deploys", en: "Deploy History" },
    detail_rollback_btn: { es: "⏪ Revertir", en: "⏪ Rollback" },
    detail_no_history: { es: "Sin deploys anteriores.", en: "No previous deploys." },
    detail_bundle_badge: { es: "bundle", en: "bundle" },
    detail_binary_badge: { es: "binario", en: "binary" },

    // Metrics
    detail_metrics_title: { es: "Métricas del Proceso", en: "Process Metrics" },
    detail_cpu: { es: "CPU", en: "CPU" },
    detail_ram: { es: "RAM", en: "RAM" },
    detail_uptime: { es: "Tiempo activo", en: "Uptime" },
    detail_metrics_idle: { es: "Proceso no activo", en: "Process not running" },

    // Settings
    detail_settings_title: { es: "Configuración", en: "Settings" },
    detail_custom_domain_title: { es: "Dominio Personalizado", en: "Custom Domain" },
    detail_custom_domain_placeholder: { es: "ej. mi-app.com", en: "e.g. my-app.com" },
    detail_custom_domain_save: { es: "Guardar Dominio", en: "Save Domain" },
    detail_ram_limit_title: { es: "Límite de RAM (MB)", en: "RAM Limit (MB)" },
    detail_ram_limit_placeholder: { es: "Sin límite", en: "No limit" },
    detail_ram_limit_save: { es: "Aplicar Límite", en: "Apply Limit" },
    detail_ram_limit_hint: { es: "Deja vacío para sin límite. El proceso se reiniciará.", en: "Leave empty for no limit. Process will restart." },

    // Landing
    land_subtitle: { 
        es: "Tu Plataforma como Servicio personal, minimalista y ultrarrápida. Despliega tus aplicaciones, usa almacenamiento S3 integrado y bases de datos SQLite al instante.", 
        en: "Your personal, minimalist and lightning-fast Platform as a Service. Deploy your apps, use built-in S3 storage and SQLite databases instantly." 
    },
    land_btn_dashboard: { es: "Ir al Dashboard", en: "Go to Dashboard" },
    land_btn_login: { es: "Acceder", en: "Sign In" },
    land_btn_docs: { es: "Leer Documentación", en: "Read Documentation" },
    land_feat1_title: { es: "🚀 Scale-to-Zero", en: "🚀 Scale-to-Zero" },
    land_feat1_desc: { 
        es: "Las aplicaciones sin tráfico se suspenden automáticamente liberando memoria, y se despiertan instantáneamente cuando llega una petición HTTP.", 
        en: "Applications without traffic are automatically suspended freeing memory, and wake up instantly when an HTTP request arrives." 
    },
    land_feat2_title: { es: "🪣 Motor S3 Nativo", en: "🪣 Native S3 Engine" },
    land_feat2_desc: { 
        es: "No necesitas AWS. Cada proyecto cuenta con un bucket S3 dedicado alojado directamente en el mismo servidor.", 
        en: "No AWS needed. Each project has a dedicated S3 bucket hosted directly on the same server." 
    },
    land_feat3_title: { es: "🔄 Integración CI/CD", en: "🔄 CI/CD Integration" },
    land_feat3_desc: {
        es: "Haz push a GitHub y observa cómo tu código se compila y se despliega mágicamente en menos de un minuto usando nuestra plantilla de Actions.",
        en: "Push to GitHub and watch your code magically build and deploy in under a minute using our Actions template."
    },
    land_feat4_title: { es: "🗄️ SQLite & Backups", en: "🗄️ SQLite & Backups" },
    land_feat4_desc: {
        es: "Tu app recibe DATABASE_URL lista para SQLx o rusqlite. Descarga backups en vivo desde el dashboard sin interrumpir el servicio.",
        en: "Your app receives a ready-to-use DATABASE_URL for SQLx or rusqlite. Download live backups from the dashboard without interrupting the service."
    },
    land_feat5_title: { es: "⚙️ Variables de Entorno", en: "⚙️ Environment Variables" },
    land_feat5_desc: {
        es: "Edita las variables de entorno de cada proyecto desde el dashboard. Los cambios se aplican al instante reiniciando el proceso.",
        en: "Edit each project's environment variables from the dashboard. Changes apply instantly by restarting the process."
    },
    land_feat6_title: { es: "👤 Multi-usuario & API Key", en: "👤 Multi-user & API Key" },
    land_feat6_desc: {
        es: "Registro multi-usuario, sesiones seguras y claves API para automatizar deploys desde tus scripts o pipelines de CI/CD.",
        en: "Multi-user registration, secure sessions and API keys to automate deploys from your scripts or CI/CD pipelines."
    },
    land_features_title: { es: "¿Qué incluye?", en: "What's included?" },
    land_how_title: { es: "¿Cómo funciona?", en: "How does it work?" },
    land_step1_title: { es: "Compila tu binario", en: "Compile your binary" },
    land_step1_desc: {
        es: "Cualquier app que compile a un binario standalone (Rust, Go, C…) es compatible. Apunta al target de tu servidor.",
        en: "Any app that compiles to a standalone binary (Rust, Go, C…) is compatible. Target your server's architecture."
    },
    land_step2_title: { es: "Haz el deploy", en: "Deploy it" },
    land_step2_desc: {
        es: "Sube el binario al API con curl o GitHub Actions. Se asigna un puerto, subdominio y variables de entorno en segundos.",
        en: "Upload the binary to the API with curl or GitHub Actions. A port, subdomain and env vars are assigned in seconds."
    },
    land_step3_title: { es: "Tu app está en línea", en: "Your app is online" },
    land_step3_desc: {
        es: "Accede por subdominio. El proxy enruta el tráfico, el S3 aislado está listo y la DB inicializada. Sin pasos adicionales.",
        en: "Access it by subdomain. The proxy routes traffic, isolated S3 is ready and DB initialized. No extra steps."
    },
    land_quickstart_title: { es: "Un comando para empezar", en: "One command to get started" },
    land_quickstart_sub: {
        es: "Compila para Linux y envía el binario. El resto es automático.",
        en: "Compile for Linux and send the binary. The rest is automatic."
    }
}

pub struct Lang(pub &'static Dict);

impl FromRequestParts<AppState> for Lang {
    type Rejection = std::convert::Infallible;

    async fn from_request_parts(
        parts: &mut Parts,
        _state: &AppState,
    ) -> Result<Self, Self::Rejection> {
        let cookie_lang = parts
            .headers
            .get(axum::http::header::COOKIE)
            .and_then(|v| v.to_str().ok())
            .and_then(|c| {
                c.split(';')
                    .map(|s| s.trim())
                    .find_map(|s| s.strip_prefix("lang="))
            });

        let accept_lang = parts
            .headers
            .get(axum::http::header::ACCEPT_LANGUAGE)
            .and_then(|v| v.to_str().ok())
            .unwrap_or("es");

        let target = cookie_lang.unwrap_or(accept_lang);

        if target.to_lowercase().starts_with("en") {
            Ok(Lang(&EN))
        } else {
            Ok(Lang(&ES))
        }
    }
}
